# Generated by Django 4.2.30 on 2026-04-12 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('room', models.CharField(blank=True, default='', max_length=50)),
                ('day_of_week', models.CharField(choices=[('1', 'Lundi'), ('2', 'Mardi'), ('3', 'Mercredi'), ('4', 'Jeudi'), ('5', 'Vendredi'), ('6', 'Samedi'), ('7', 'Dimanche')], default='1', max_length=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('schedule_type', models.CharField(choices=[('cours', 'Cours'), ('controle', 'Contrôle'), ('examen', 'Examen'), ('rattrapage', 'Rattrapage')], default='cours', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_schedule',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
