# Generated by Django 4.2.30 on 2026-05-05 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_course_enrollment_lesson_certificate_studentofmonth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cv_data', models.JSONField(blank=True, default=dict)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cv_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cvs',
                'ordering': ['-updated_at'],
            },
        ),
    ]
