# Generated by Django 4.2.30 on 2026-05-06 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='accounts.lesson')),
            ],
            options={
                'db_table': 'lesson_videos',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='accounts.lessonvideo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'video_completions',
                'unique_together': {('user', 'lesson_video')},
            },
        ),
    ]
